services:

  app:
    container_name: boilerplate_app
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    command: bash -c "uv run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    restart: always